# This is config.yaml
# Default configuration
api:
  model: "mixtral-8x7b-32768"
  max_tokens: 2048
  temperature: 0.7

agents:
  max_iterations: 3
  concurrent_agents: true

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"